name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.9.0'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install nbconvert==5.6.1 ipython_genutils jinja2==3.0.3

      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: Install QuantumOptics.jl
        run: |
          julia -e "import Pkg; Pkg.add(\"QuantumOptics\");"

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key

        run: julia --project=docs/ docs/make.jl
